# fly.toml app configuration file generated for eeee-e67eceb8-29a8-4446-a481-989e9c598404-1718872270-server on 2024-06-20T08:31:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eeee-e67eceb8-29a8-4446-a481-989e9c598404-1718872270-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
